### ISSUE TITLE
Please add c# files used in your demo

### ISSUE THREAD

**Issue by ayushoriginal** [sethjuarez/DeepLearningWithPyTorch#1]
Hi Seth,
Can you please add the c# files (example- main.cs) used in your demo at https://www.youtube.com/watch?v=lamnwHvjEV0 corresponding to the MNIST example?
Thanks!

**Comment by sethjuarez** [comment]
You can find those in the [Numbers](https://github.com/sethjuarez/Numbers) repo. Hope this helps!
